<?
$MESS["ALIN_VISION_MESSAGE"] = "Версия для слабовидящих";
$MESS["ALIN_VISION_KNOPKA_NAJATA"] = "Кнопка нажата!";
$MESS["ALIN_VISION_RAZMER_SRIFTA"] = "Размер шрифта</p><br/><div class='btn-group'><button type='button' id='a2' class='btn btn-default btn-sm'><span class='glyphicon glyphicon-minus'></span></button><button type='button' id='a1' class='btn btn-default btn-sm'><span class='glyphicon glyphicon-plus'></span></button></div></div><div class='ccol-md-2 col-centered'><p>Шрифт</p><br/><div class='btn-group'><button type='button' class='btn btn-default btn-sm nop'  id='font1'><span style='font-family:'Times New Roman';font-size:14px;'>с засечками</span></button><button type='button' class='btn btn-default btn-sm nop' id='font2'><span style='font-family:'Arial';font-size:14px;'>без засечек</span></button></div></div><div class='ccol-md-3 col-centered'><p><span>Цвета сайта</span></p><br/><div class='btn-group'><button type='button' class='btn btn-default btn-sm' id='c1'><span class='glyphicon glyphicon-font'></span></button><button type='button' class='btn btn-default btn-sm' id='c2'><span class='glyphicon glyphicon-font'></span></button><button type='button' class='btn btn-default btn-sm' id='c3'><span class='glyphicon glyphicon-font'></span></button><button type='button' class='btn btn-default btn-sm' id='c4'><span class='glyphicon glyphicon-font'></span></button><button type='button' class='btn btn-default btn-sm' id='c5'><span class='glyphicon glyphicon-font'></span></button></div></div><div class='ccol-md-2 col-centered'><p>Изображения</p><br/><div class='btn-group' data-toggle='buttons'><label class='btn btn-default  btn-sm redis'><input type='radio' id='q156' name='imgvis' value='1' /><span class='glyphicon glyphicon-eye-open'></span></label><label class='btn btn-default  btn-sm redis'><input type='radio' id='q157' name='imgvis' value='2' /><span class='glyphicon glyphicon-eye-close'></span></label></div></div><div class='ccol-md-1 col-centered'><p><span class='glyphicon glyphicon-resize-horizontal'>Инт.</span></p><br/><div class='btn-group'><button type='button' id='i2' class='btn btn-default btn-sm'><span class='glyphicon glyphicon-minus'></span></button><button type='button' id='i1' class='btn btn-default btn-sm'><span class='glyphicon glyphicon-plus'></span></button></div></div><div class='ccol-md-1 col-centered'><p><span class='glyphicon glyphicon-resize-vertical'>Инт.</span></p><br/><div class='btn-group'><div class='btn-group' data-toggle='buttons'><label class='btn btn-default  btn-sm ol1'><input type='radio' id='yr1' name='inter' value='1' /><span class='glyphicon glyphicon-resize-small'></span></label><label class='btn btn-default btn-sm ol1'><input type='radio' id='yr2' name='inter' value='2' /><span class='glyphicon glyphicon-resize-full'></span></label></div></div></div><div class='ccol-md-1 col-centered'><p></p><br/><div class='btn-group'><button class='btn btn-default btn-sm' id='reset'><i class='glyphicon glyphicon-refresh'></i>Сброс";
$MESS["ALIN_VISION_VERNUTQSA_NA_OBYCNUU"] = "Вернуться на обычную версию сайта'>";
$MESS["ALIN_VISION_VERSIA_DLA_SLABOVIDA"] = "Версия для слабовидящих'>";
$MESS["ALIN_VISION_RAZMER_SRIFTA1"] = "Размер шрифта";
$MESS["ALIN_VISION_SRIFT"] = "Шрифт";
$MESS["ALIN_VISION_S_ZASECKAMI"] = "с засечками";
$MESS["ALIN_VISION_BEZ_ZASECEK"] = "без засечек";
$MESS["ALIN_VISION_CVETA_SAYTA"] = "Цвета сайта";
$MESS["ALIN_VISION_IZOBRAJENIA"] = "Изображения";
$MESS["ALIN_VISION_INT"] = "Инт.";
$MESS["ALIN_VISION_SBROS"] = "Сброс";
$MESS["GCNT_MAIN_HEADER_HAVE_NOT_EYE_TEXT"] = "Версия для<br>слабовидящих";
$MESS["GCNT_MAIN_HEADER_HAVE_NOT_EYE_TEXT_TITLE"] = "Версия для слабовидящих";
?>